using AnalyzerApi.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace AnalyzerApi.Services
{
    public class PdfReportService
    {
        public byte[] GeneratePdf(AnalysisResult result)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Text("API Analysis Report")
                        .FontSize(22)
                        .Bold()
                        .FontColor(Colors.Blue.Medium);

                    page.Content().PaddingVertical(10).Column(col =>
                    {
                        col.Item().Text("Summary")
                            .FontSize(16)
                            .Bold();

                        col.Item()
                            .PaddingBottom(10)
                            .Text(result.Summary);

                        col.Item().Text("Full Report")
                            .FontSize(16)
                            .Bold();

                        col.Item()
                            .PaddingBottom(10)
                            .Text(result.FullReport);

                        col.Item().Text("API URL")
                            .FontSize(16)
                            .Bold();

                        col.Item()
                            .PaddingBottom(10)
                            .Text(result.TargetApiBaseUrl ?? "-");

                        col.Item().Text("Health Status")
                            .FontSize(16)
                            .Bold();

                        col.Item()
                            .PaddingBottom(20)
                            .Text(result.HealthCheckStatus ?? "-");

                        col.Item().Text("Analyzed Files")
                            .FontSize(16)
                            .Bold();

                        foreach (var file in result.FilesAnalyzed)
                        {
                            col.Item()
                                .PaddingBottom(5)
                                .Text($"File: {file.RelativePath}")
                                .FontSize(13)
                                .Bold()
                                .FontColor(Colors.Grey.Darken1);

                            col.Item()
                                .Background(Colors.Grey.Lighten3)
                                .Padding(5)
                                .Text(file.Content)
                                .FontSize(10);

                            col.Item().PaddingBottom(15);
                        }
                    });

                    page.Footer().AlignCenter().Text(text =>
                    {
                        text.Span("Generated by AnalyzerApi ").FontSize(10);
                    });
                });
            });

            return document.GeneratePdf();
        }
    }
}
